apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"argo-role","namespace":"argo"},"rules":[{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create","get","update"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["get"]}]}
  creationTimestamp: "2023-11-03T12:16:08Z"
  name: argo-role
  namespace: argo
  resourceVersion: "549"
  uid: d6cc339a-8fb7-4774-8137-d0a0851f0ab3
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
