apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: tf-mnist
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      image: "emacski/tensorflow-serving:2.6.0"
      storageUri: "pvc://strategy-volume/saved_model_versions"
