apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: tfjob-wf-    # name of the workflow spec
spec:
  entrypoint: tfjob-wf          # invoke the tfjob template
  templates:
  - name: tfjob-wf
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: data-ingestion-step            # data-ingestion-step is run before the following steps
        template: data-ingestion
    - - name: distributed-training-step      # double dash => run after previous step
        template: distributed-training
    - - name: model-selection-step
        template: model-selection
    - - name: model-serving-step
        template: model-serving
podGC:
  strategy: OnPodSuccess
volumes:
- name: model
  persistentVolumeClaim:
    claimName: strategy-volume